apiVersion: v1
kind: ServiceAccount
metadata:
  name: spicedb-proxy-integration
  namespace: spicedb-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spicedb-proxy-integration
rules:
# Core API groups
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
# Apps
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
# Extensions
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]
# Custom Resource Definitions
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
# All other API groups (for comprehensive access)
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spicedb-proxy-integration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spicedb-proxy-integration
subjects:
- kind: ServiceAccount
  name: spicedb-proxy-integration
  namespace: spicedb-proxy